### ISSUE TITLE
Regex not working

### ISSUE THREAD

**Issue by XurxoMF** [AzureDoom/Log-Begone#1]
Maybe I'm doing something wrong, but the regular expressions are not working correctly.

I have these expressions:
regex = ["1", "^1", "1$", "^ 1", " 1$", "\b1\b", "\b[1]{1}\b"]

In theory it should delete these messages but it does not do it:
[17:06:47] [Worker-Main-3/INFO]: 1
[17:06:47] [Worker-Main-20/INFO]: 1

If I am doing something wrong I would like to know what it is, if not I would like it to be fixed in future versions.

I'm using fabric, 1.19.2

Love the mod btw <3

**Comment by AzureDoom** [comment]
Can you please the mod causing the logging? This will help me in resolving the issue for you!

**Comment by XurxoMF** [comment]
Of course, it is a link to curseforge
[Log-Begone-Fabric-1.19-1.0.2.jar](https://www.curseforge.com/minecraft/mc-mods/log-begone/files/4014378)

Edit: If you need a .log from the server or something just ask me <3

**Comment by AzureDoom** [comment]
No the mod causing the 1 and such

**Comment by XurxoMF** [comment]
Oh, idk, is not a mod I thought. These messages just pop up repeatedly as you explore the world

I am using 260 + mods, it is difficult to know what is the cause, but I think it is the fabric itself or the vanilla server.

**Comment by AzureDoom** [comment]
Do you have deeper dark?

**Comment by XurxoMF** [comment]
Yes, deeper darker 1.1.4

**Comment by XurxoMF** [comment]
Hihi, any news? <3

**Comment by AzureDoom** [comment]
I will not be able to work on this for a while due to work and holidays.

**Comment by XurxoMF** [comment]
Oh, ok, no rush. Just let me know if u need something about the error :)

**Comment by AzureDoom** [comment]
A fix should now be released for this, please test when you can!

**Comment by XurxoMF** [comment]
Sure, tomorrow I'll have free time so i'll try it

**Comment by XurxoMF** [comment]
I updated the mod and used "\b1\b" and it doesn't work ;-;
It doesn't seem to be a bug in your mod but in the one that is generating the 1.
