### ISSUE TITLE
[1.20.1-Forge] Mod doesn't seem to work.

### ISSUE THREAD

**Issue by Gbergz** [AzureDoom/Log-Begone#4]
^

Mod is not working it seems, I block entries in the config but they still spam & show up in the console.

Versions:
Minecraft: 1.20.1
Forge: 47.1.3
Log Begone: 1.0.8

**Comment by AzureDoom** [comment]
What is your config setup as?

**Comment by Gbergz** [comment]
As in what entries I have in it?

**Comment by AzureDoom** [comment]
Yes!

**Comment by Gbergz** [comment]
https://gist.githubusercontent.com/Gbergz/b89554517c65f63084bb3805ec53631d/raw/6567fb11a0604ba41940f2941665fbb7742878d0/logbegone.toml

**Comment by Gbergz** [comment]
I'll send it as a txt file bcs this doesn't support uploading  .toml files:
[logbegone.txt](https://github.com/AzureDoom/Log-Begone/files/12073003/logbegone.txt)

**Comment by AzureDoom** [comment]
What exactly isn't working? I've tested my end and it's removing for me.

**Comment by Gbergz** [comment]
Every entry that I blocked in the config still shows up in logs etc.

**Comment by Gbergz** [comment]
Update on this, it's still isn't functioning for me, I add the lines to config, but in the latest.log all errors tied to that still shows up. I'm at a loss.

**Comment by Gbergz** [comment]
Tried regex too, that isn't working either. You can test this yourself if you want in the modpack [TNP Limitless 7](https://www.curseforge.com/minecraft/modpacks/tnp-limitless-7).

**Comment by Exzept1on** [comment]
same issue, not working

**Comment by Gbergz** [comment]
This issue should be re-opened.

**Comment by AzureDoom** [comment]
Works fine om 47.1.3, any version past that is unsupported because I don't support Forge anymore. Only NeoForge and Fabric, so this won't be reopened

**Comment by Gbergz** [comment]
Doesn't work on 47.1.3 either.

**Comment by AzureDoom** [comment]
Works just fine in my modpack on 47.1.3, so yes its working perfectly
