### ISSUE TITLE
crash on neoforge 47.1.76 (1.20.1)

### ISSUE THREAD

**Issue by SaraNekoTH** [AzureDoom/Log-Begone#5]
[crash-2023-09-16_20.17.12-fml.txt](https://github.com/AzureDoom/Log-Begone/files/12640775/crash-2023-09-16_20.17.12-fml.txt)

**Comment by AzureDoom** [comment]
This is showing an issue with your config, can you share it?

**Comment by SaraNekoTH** [comment]
> This is showing an issue with your config, can you share it?

sorry i just deteled that instances after that :(
i remember that that all default setting for all of mod
may you want to looking for all of that ? i can try again with new instances almost likely same mod setting.

**Comment by SaraNekoTH** [comment]
> This is showing an issue with your config, can you share it?

looking nice and likely same :)

[config.zip](https://github.com/AzureDoom/Log-Begone/files/12640977/config.zip)

**Comment by AzureDoom** [comment]
This will be fixed as soon as I have moved this to a proper multi loader format here soon, as I'll be building directly against NeoForge and Fabric then.
