### ISSUE TITLE
Does not seem to remove OpenGL debug spam

### ISSUE THREAD

**Issue by CompeyDev** [AzureDoom/Log-Begone#6]
With v1.0.8 of the mod, GL_INVALID_OPERATION log spam messages do not seem to be suppressed.

![openGL log spam](https://github.com/AzureDoom/Log-Begone/assets/74418041/f43c69ed-253e-4eea-b8e4-3c0eca4ea976)

**Comment by AzureDoom** [comment]
Please show your config

**Comment by CompeyDev** [comment]
Where? The README on the Modrinth page don't specify that this mod supports configuration. Thought you could not configure things like custom regexes.

**Comment by CompeyDev** [comment]
Got it, will include my own regex for this log, but it would be nice to have a note on README on how to configure the file since there isn't any in-game configuration.

**Comment by eehunter** [comment]
Could you share the config you used to fix it? I have nearly the _exact_ same message being spammed and I can't figure out how to configure this mod.

**Comment by eehunter** [comment]
Okay, the reason it didn't work for me was because I forgot to add commas when adding new entries to the JSON arrays. Oops.
