### ISSUE TITLE
There is still a log spam.

### ISSUE THREAD

**Issue by sadlyborger** [AzureDoom/Log-Begone#7]
![image](https://github.com/user-attachments/assets/0e402623-f9b8-4063-b8db-2f2ad1aba8a2)
This is our logs, would it be possible to fix it?

**Comment by AzureDoom** [comment]
Show config

**Comment by sadlyborger** [comment]
Hello, sorry for late reply. What config should I send?

**Comment by AzureDoom** [comment]
It's called log-begone in your config folder

**Comment by sadlyborger** [comment]
Hello, this is what it has
[logbegone.json](https://github.com/user-attachments/files/16260796/logbegone.json)

**Comment by AzureDoom** [comment]
That's a default config, you have to actaully configure it with the messages.
